### ISSUE TITLE
Chào Bro!

### ISSUE THREAD

**Issue by henzycuong1** [TungPhamDuy/candlestick-pattern-detector#1]
Chào Bro.
Lang thang tìm lib trên github thì bắt gặp project của bro. 
Bro cho mình hỏi khi live trading thì có bản fork nào của talib hỗ trợ cho việc live trading ko bro ?
Cám ơn bro

**Comment by TungPhamDuy** [comment]
Hi bro, 
Thank kiu ông vì đã quan tâm pj của tui nhé!
Talib là chỉ là một lib chứa các formular để tính các chỉ số hoi, nên nó sẽ tuỳ thuộc vào data ông pull về có dc update liên tục hay không để chạy. Mà tui k recmd dùng Talib vì nó k thể cmd install trực tiếp trên các IDE hiện tại mà phải xài qua wrapper á. Nếu bro vẫn mún dùng thì tui recmd lib "ta" same function but tiện lợi hơn.
Với live trade thì cả 2 lib đều k hỗ trợ, tuy nhiên ông có thể tìm hiểu về Pine script được integrate sẵn trên tradingview khá là thuận tiện để code, chạy, backtest và exe lệnh với live data ở trển nhé!

**Comment by henzycuong1** [comment]
> Hi bro, Thank kiu ông vì đã quan tâm pj của tui nhé! Talib là chỉ là một lib chứa các formular để tính các chỉ số hoi, nên nó sẽ tuỳ thuộc vào data ông pull về có dc update liên tục hay không để chạy. Mà tui k recmd dùng Talib vì nó k thể cmd install trực tiếp trên các IDE hiện tại mà phải xài qua wrapper á. Nếu bro vẫn mún dùng thì tui recmd lib "ta" same function but tiện lợi hơn. Với live trade thì cả 2 lib đều k hỗ trợ, tuy nhiên ông có thể tìm hiểu về Pine script được integrate sẵn trên tradingview khá là thuận tiện để code, chạy, backtest và exe lệnh với live data ở trển nhé!

Pinescript tôi thấy nếu viết ở dạng project thì thành sớ văn quá. Gần như thằng Pinescript chủ yếu là để cho việc viết Indicator, còn về viết bot chạy live thì tôi thấy ko ổn lắm.
Cám ơn bro đã hồi đáp :D
